name: Stamp build date and hash

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # needed to push the updated index.html

jobs:
  stamp:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Compute build values
        id: vals
        run: |
          SHORT_HASH="${GITHUB_SHA:0:7}"
          TZ="America/New_York" date '+%Y-%m-%d %H:%M %Z' > .buildtime
          BUILD_TIME=$(cat .buildtime)
          echo "short=$SHORT_HASH" >> "$GITHUB_OUTPUT"
          echo "time=$BUILD_TIME"   >> "$GITHUB_OUTPUT"

      - name: Update build marker in index.html
        run: |
          HASH="${{ steps.vals.outputs.short }}"
          TIME="${{ steps.vals.outputs.time }}"

          # Replace the FIRST line that starts with <!-- build:
          awk -v rep="<!-- build: ${TIME} / commit: ${HASH} -->" '
            c==0 && /^<!--[[:space:]]*build:/ { print rep; c=1; next }
            { print }
          ' index.html > index.html.tmp && mv index.html.tmp index.html

      - name: Commit if changed
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add index.html
            git commit -m "chore: stamp build date/hash [skip ci]"
            git push
          fi
